In [2]:
import pandas as pd
import csv
import os
import seaborn as sns

from sklearn.metrics import f1_score

In [3]:
# load csv files with results from different models
results = {}
directory = '../0_results/month-models'
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        results[os.path.splitext(filename)[0]] = pd.read_csv(os.path.join(directory, filename))
        continue
    else:
        continue

In [4]:
# calculate f1 
f1_type = 'macro'
scores = {}

for key in results:
    scores[key] = f1_score(results[key]['label'], results[key]['prediction'], average=f1_type)

score_series = {}
for model in sorted(pd.unique(pd.Series(scores.keys()).str[:17])):
    score_series[model] = []
    for key in sorted(scores):
        if model in key:
            score_series[model].append(scores[key])

out_df = pd.DataFrame.from_dict(score_series).reset_index().rename(columns={'index':'y-m'})
out_df.columns = out_df.columns.str.replace('bert-base-', '')
out_df['y-m'] = out_df['y-m'].apply(lambda x: f'2018-0{x+1}')

out_df['mean'] = out_df.mean(axis=1)

def color(val):
    color = 'red' if val < 0.9 else 'green'
    return 'background-color: %s' % color

cm = sns.light_palette('green', as_cmap=True)
out_df.style.background_gradient(cmap=cm, low = 0, high = 1.0)